export declare const handlers: {
    generic: (fn: Function) => (this: any, e?: Event | undefined) => any;
    abort: (fn: Function) => (this: any, e?: Event | UIEvent | undefined) => any;
    afterprint: (fn: Function) => (this: any, e?: Event | undefined) => any;
    animationend: (fn: Function) => (this: any, e?: Event | AnimationEvent | undefined) => any;
    animationiteration: (fn: Function) => (this: any, e?: Event | AnimationEvent | undefined) => any;
    animationstart: (fn: Function) => (this: any, e?: Event | AnimationEvent | undefined) => any;
    beforeprint: (fn: Function) => (this: any, e?: Event | undefined) => any;
    beforeunload: (fn: Function) => (this: any, e?: Event | UIEvent | undefined) => any;
    blur: (fn: Function) => (this: any, e?: Event | FocusEvent | undefined) => any;
    canplay: (fn: Function) => (this: any, e?: Event | undefined) => any;
    canplaythrough: (fn: Function) => (this: any, e?: Event | undefined) => any;
    change: (fn: Function) => (this: any, e?: Event | undefined) => any;
    click: (fn: Function) => (this: any, e?: Event | MouseEvent | undefined) => any;
    contextmenu: (fn: Function) => (this: any, e?: Event | MouseEvent | undefined) => any;
    copy: (fn: Function) => (this: any, e?: Event | ClipboardEvent | undefined) => any;
    cut: (fn: Function) => (this: any, e?: Event | ClipboardEvent | undefined) => any;
    dblclick: (fn: Function) => (this: any, e?: Event | MouseEvent | undefined) => any;
    drag: (fn: Function) => (this: any, e?: Event | DragEvent | undefined) => any;
    dragend: (fn: Function) => (this: any, e?: Event | DragEvent | undefined) => any;
    dragenter: (fn: Function) => (this: any, e?: Event | DragEvent | undefined) => any;
    dragleave: (fn: Function) => (this: any, e?: Event | DragEvent | undefined) => any;
    dragover: (fn: Function) => (this: any, e?: Event | DragEvent | undefined) => any;
    dragstart: (fn: Function) => (this: any, e?: Event | DragEvent | undefined) => any;
    drop: (fn: Function) => (this: any, e?: Event | DragEvent | undefined) => any;
    durationchange: (fn: Function) => (this: any, e?: Event | undefined) => any;
    ended: (fn: Function) => (this: any, e?: Event | undefined) => any;
    error: (fn: Function) => (this: any, e?: Event | undefined) => any;
    focus: (fn: Function) => (this: any, e?: Event | FocusEvent | undefined) => any;
    focusin: (fn: Function) => (this: any, e?: Event | FocusEvent | undefined) => any;
    focusout: (fn: Function) => (this: any, e?: Event | FocusEvent | undefined) => any;
    fullscreenchange: (fn: Function) => (this: any, e?: Event | undefined) => any;
    fullscreenerror: (fn: Function) => (this: any, e?: Event | undefined) => any;
    hashchange: (fn: Function) => (this: any, e?: Event | HashChangeEvent | undefined) => any;
    input: (fn: Function) => (this: any, e?: Event | InputEvent | undefined) => any;
    invalid: (fn: Function) => (this: any, e?: Event | undefined) => any;
    keydown: (fn: Function) => (this: any, e?: Event | KeyboardEvent | undefined) => any;
    keypress: (fn: Function) => (this: any, e?: Event | KeyboardEvent | undefined) => any;
    keyup: (fn: Function) => (this: any, e?: Event | KeyboardEvent | undefined) => any;
    load: (fn: Function) => (this: any, e?: Event | UIEvent | undefined) => any;
    loadeddata: (fn: Function) => (this: any, e?: Event | undefined) => any;
    loadedmetadata: (fn: Function) => (this: any, e?: Event | undefined) => any;
    loadstart: (fn: Function) => (this: any, e?: Event | ProgressEvent<EventTarget> | undefined) => any;
    message: (fn: Function) => (this: any, e?: Event | undefined) => any;
    mousedown: (fn: Function) => (this: any, e?: Event | MouseEvent | undefined) => any;
    mouseenter: (fn: Function) => (this: any, e?: Event | MouseEvent | undefined) => any;
    mouseleave: (fn: Function) => (this: any, e?: Event | MouseEvent | undefined) => any;
    mousemove: (fn: Function) => (this: any, e?: Event | MouseEvent | undefined) => any;
    mouseover: (fn: Function) => (this: any, e?: Event | MouseEvent | undefined) => any;
    mouseout: (fn: Function) => (this: any, e?: Event | MouseEvent | undefined) => any;
    mouseup: (fn: Function) => (this: any, e?: Event | MouseEvent | undefined) => any;
    mousewheel: (fn: Function) => (this: any, e?: Event | WheelEvent | undefined) => any;
    offline: (fn: Function) => (this: any, e?: Event | undefined) => any;
    online: (fn: Function) => (this: any, e?: Event | undefined) => any;
    open: (fn: Function) => (this: any, e?: Event | undefined) => any;
    pagehide: (fn: Function) => (this: any, e?: Event | PageTransitionEvent | undefined) => any;
    pageshow: (fn: Function) => (this: any, e?: Event | PageTransitionEvent | undefined) => any;
    paste: (fn: Function) => (this: any, e?: Event | ClipboardEvent | undefined) => any;
    pause: (fn: Function) => (this: any, e?: Event | undefined) => any;
    play: (fn: Function) => (this: any, e?: Event | undefined) => any;
    playing: (fn: Function) => (this: any, e?: Event | undefined) => any;
    popstate: (fn: Function) => (this: any, e?: Event | PopStateEvent | undefined) => any;
    progress: (fn: Function) => (this: any, e?: Event | undefined) => any;
    ratechange: (fn: Function) => (this: any, e?: Event | undefined) => any;
    resize: (fn: Function) => (this: any, e?: Event | UIEvent | undefined) => any;
    reset: (fn: Function) => (this: any, e?: Event | undefined) => any;
    scroll: (fn: Function) => (this: any, e?: Event | UIEvent | undefined) => any;
    search: (fn: Function) => (this: any, e?: Event | undefined) => any;
    seeked: (fn: Function) => (this: any, e?: Event | undefined) => any;
    seeking: (fn: Function) => (this: any, e?: Event | undefined) => any;
    select: (fn: Function) => (this: any, e?: Event | UIEvent | undefined) => any;
    show: (fn: Function) => (this: any, e?: Event | undefined) => any;
    stalled: (fn: Function) => (this: any, e?: Event | undefined) => any;
    storage: (fn: Function) => (this: any, e?: Event | StorageEvent | undefined) => any;
    submit: (fn: Function) => (this: any, e?: Event | undefined) => any;
    suspend: (fn: Function) => (this: any, e?: Event | undefined) => any;
    timeupdate: (fn: Function) => (this: any, e?: Event | undefined) => any;
    toggle: (fn: Function) => (this: any, e?: Event | undefined) => any;
    touchcancel: (fn: Function) => (this: any, e?: Event | TouchEvent | undefined) => any;
    touchend: (fn: Function) => (this: any, e?: Event | TouchEvent | undefined) => any;
    touchmove: (fn: Function) => (this: any, e?: Event | TouchEvent | undefined) => any;
    touchstart: (fn: Function) => (this: any, e?: Event | TouchEvent | undefined) => any;
    transitionend: (fn: Function) => (this: any, e?: Event | TransitionEvent | undefined) => any;
    unload: (fn: Function) => (this: any, e?: Event | UIEvent | undefined) => any;
    volumechange: (fn: Function) => (this: any, e?: Event | undefined) => any;
    waiting: (fn: Function) => (this: any, e?: Event | undefined) => any;
    wheel: (fn: Function) => (this: any, e?: Event | WheelEvent | undefined) => any;
};
export type HandlerFactories = typeof handlers;
export type Handlers = {
    [e in keyof HandlerFactories]?: ReturnType<HandlerFactories[e]>;
};
